/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkedSolutionRouteImport } from './routes/api/worked-solution'
import { Route as ApiFlashcardsRouteImport } from './routes/api/flashcards'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkedSolutionRoute = ApiWorkedSolutionRouteImport.update({
  id: '/api/worked-solution',
  path: '/api/worked-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlashcardsRoute = ApiFlashcardsRouteImport.update({
  id: '/api/flashcards',
  path: '/api/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/flashcards': typeof ApiFlashcardsRoute
  '/api/worked-solution': typeof ApiWorkedSolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/flashcards': typeof ApiFlashcardsRoute
  '/api/worked-solution': typeof ApiWorkedSolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/flashcards': typeof ApiFlashcardsRoute
  '/api/worked-solution': typeof ApiWorkedSolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/flashcards' | '/api/worked-solution'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/flashcards' | '/api/worked-solution'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/flashcards'
    | '/api/worked-solution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFlashcardsRoute: typeof ApiFlashcardsRoute
  ApiWorkedSolutionRoute: typeof ApiWorkedSolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/worked-solution': {
      id: '/api/worked-solution'
      path: '/api/worked-solution'
      fullPath: '/api/worked-solution'
      preLoaderRoute: typeof ApiWorkedSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flashcards': {
      id: '/api/flashcards'
      path: '/api/flashcards'
      fullPath: '/api/flashcards'
      preLoaderRoute: typeof ApiFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFlashcardsRoute: ApiFlashcardsRoute,
  ApiWorkedSolutionRoute: ApiWorkedSolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
